In [22]:
from datetime import datetime, timedelta
import yfinance as yf
import pandas as pd
import numpy as np

# List of company
nifty50_tickers = ['^NSEI',
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'HINDUNILVR.NS', 
    'ITC.NS', 'KOTAKBANK.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'LT.NS', 'BAJFINANCE.NS', 
    'ASIANPAINT.NS', 'HCLTECH.NS', 'MARUTI.NS', 'TITAN.NS', 'AXISBANK.NS', 'SUNPHARMA.NS', 
    'NTPC.NS', 'ONGC.NS', 'NESTLEIND.NS', 'ULTRACEMCO.NS', 'WIPRO.NS', 'ADANIPORTS.NS', 
    'POWERGRID.NS', 'M&M.NS', 'BAJAJ-AUTO.NS', 'GRASIM.NS', 'TECHM.NS', 'JSWSTEEL.NS', 
    'TATASTEEL.NS', 'DRREDDY.NS', 'BRITANNIA.NS', 'EICHERMOT.NS', 'SHREECEM.NS', 
    'INDUSINDBK.NS', 'DIVISLAB.NS', 'COALINDIA.NS', 'UPL.NS', 'BPCL.NS', 'IOC.NS', 
    'CIPLA.NS', 'HEROMOTOCO.NS', 'GAIL.NS', 'SBILIFE.NS', 'HDFCLIFE.NS', 'TATAMOTORS.NS', 
    'VEDL.NS'
]

# fetching data for 'year = 5'
def fetch_data(company, year):
    end_date = datetime.today()
    start_date = end_date - timedelta(days=year*365)
    
    # Fetch historical data for Nifty 50
    df = yf.download(company, start=start_date, end=end_date)
    return (df[(  'High', company)]+df[(  'Low', company)])/2
# for each company fetching 1 data per day
# which is mean of low and high of that perticular day

data= pd.DataFrame()

# here is main code for fetch data
for i in nifty50_tickers:
    data[i] = fetch_data(i,10)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [23]:
# initialising available amount for perticular company and 
amount = {'^NSEI':500000}
invest={'^NSEI':500000}
for i in data.columns[1:]:
    amount[i] = 500000/len(data.columns[1:])
    invest[i] = 0

In [24]:
# code for buy and sall
for date in data.index:
    for col in data.columns:
        if data.loc[date,col] == np.nan:
            invest[col]=0
        

# code to buy and sell

In [25]:
amount

{'^NSEI': 500000,
 'RELIANCE.NS': 10416.666666666666,
 'TCS.NS': 10416.666666666666,
 'HDFCBANK.NS': 10416.666666666666,
 'ICICIBANK.NS': 10416.666666666666,
 'INFY.NS': 10416.666666666666,
 'HINDUNILVR.NS': 10416.666666666666,
 'ITC.NS': 10416.666666666666,
 'KOTAKBANK.NS': 10416.666666666666,
 'SBIN.NS': 10416.666666666666,
 'BHARTIARTL.NS': 10416.666666666666,
 'LT.NS': 10416.666666666666,
 'BAJFINANCE.NS': 10416.666666666666,
 'ASIANPAINT.NS': 10416.666666666666,
 'HCLTECH.NS': 10416.666666666666,
 'MARUTI.NS': 10416.666666666666,
 'TITAN.NS': 10416.666666666666,
 'AXISBANK.NS': 10416.666666666666,
 'SUNPHARMA.NS': 10416.666666666666,
 'NTPC.NS': 10416.666666666666,
 'ONGC.NS': 10416.666666666666,
 'NESTLEIND.NS': 10416.666666666666,
 'ULTRACEMCO.NS': 10416.666666666666,
 'WIPRO.NS': 10416.666666666666,
 'ADANIPORTS.NS': 10416.666666666666,
 'POWERGRID.NS': 10416.666666666666,
 'M&M.NS': 10416.666666666666,
 'BAJAJ-AUTO.NS': 10416.666666666666,
 'GRASIM.NS': 10416.666666666666,
 'TECHM.NS': 10416.666666666666,
 'JSWSTEEL.NS': 10416.666666666666,
 'TATASTEEL.NS': 10416.666666666666,
 'DRREDDY.NS': 10416.666666666666,
 'BRITANNIA.NS': 10416.666666666666,
 'EICHERMOT.NS': 10416.666666666666,
 'SHREECEM.NS': 10416.666666666666,
 'INDUSINDBK.NS': 10416.666666666666,
 'DIVISLAB.NS': 10416.666666666666,
 'COALINDIA.NS': 10416.666666666666,
 'UPL.NS': 10416.666666666666,
 'BPCL.NS': 10416.666666666666,
 'IOC.NS': 10416.666666666666,
 'CIPLA.NS': 10416.666666666666,
 'HEROMOTOCO.NS': 10416.666666666666,
 'GAIL.NS': 10416.666666666666,
 'SBILIFE.NS': 10416.666666666666,
 'HDFCLIFE.NS': 10416.666666666666,
 'TATAMOTORS.NS': 10416.666666666666,
 'VEDL.NS': 10416.666666666666}

In [6]:
data

,^NSEI,RELIANCE.NS,TCS.NS,HDFCBANK.NS,ICICIBANK.NS,INFY.NS,HINDUNILVR.NS,ITC.NS,KOTAKBANK.NS,SBIN.NS,...,UPL.NS,BPCL.NS,IOC.NS,CIPLA.NS,HEROMOTOCO.NS,GAIL.NS,SBILIFE.NS,HDFCLIFE.NS,TATAMOTORS.NS,VEDL.NS
Date,,,,,,,,,,,,,,,,,,,,,
2015-03-30,8436.524902,166.774456,1067.507282,474.500630,261.811430,433.883510,738.060555,161.117934,648.650092,242.084359,...,265.837546,72.055913,31.726900,659.875665,1898.478778,49.238521,NaN,NaN,527.021001,61.493617
2015-03-31,8502.300293,170.571494,1067.622683,475.182820,263.342198,438.100029,746.199479,162.023884,652.290661,244.289261,...,269.842174,74.848819,32.983794,665.460507,1917.070601,50.056064,NaN,NaN,539.306971,62.733273
2015-04-01,8534.075195,170.695462,1066.658016,474.049711,264.128192,426.281716,752.753370,163.103536,664.479427,244.493830,...,266.650506,76.232280,33.541166,666.586839,1923.788026,50.049556,NaN,NaN,547.661519,61.836148
2015-04-06,8620.649902,171.449714,1061.865659,475.622203,266.755149,425.097933,768.174379,166.479039,684.943088,248.653597,...,268.246314,76.291313,33.579527,680.807025,1929.253399,51.235149,NaN,NaN,560.713217,61.966639
2015-04-07,8640.224609,171.733857,1078.643796,476.824777,264.128219,422.720478,778.176504,168.774859,691.615294,248.517196,...,279.974008,75.405968,33.624653,688.527195,1922.499841,52.336081,NaN,NaN,558.676685,63.361268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-19,22874.324219,1246.025024,3504.875000,1741.599976,1310.225037,1587.900024,2203.150024,406.675003,2034.125000,744.199982,...,642.450012,264.750000,126.605000,1505.750000,3551.500000,164.619995,1471.950012,653.275024,682.149994,462.324997
2025-03-20,23095.324219,1261.525024,3545.474976,1761.650024,1317.650024,1611.950012,2218.674927,404.274994,2027.700012,748.450012,...,647.774994,268.839996,129.209999,1506.524963,3597.625000,167.014999,1497.400024,668.724976,685.850006,467.700012
2025-03-21,23267.750000,1275.549988,3540.625000,1764.825012,1330.299988,1583.775024,2240.500000,404.600006,2066.300049,751.299988,...,658.475006,278.455002,131.099998,1519.450012,3661.824951,172.864998,1523.375000,675.074982,696.774994,467.574997
2025-03-24,23571.125000,1295.125000,3608.175049,1789.025024,1359.025024,1589.899963,2253.500000,409.225006,2137.250000,769.024994,...,663.100006,282.649994,132.849998,1525.099976,3635.100098,182.299995,1562.849976,681.524994,709.774994,470.849991
2025-03-25,23735.500000,1295.149963,3674.000000,1822.599976,1346.925049,1620.575012,2267.675049,411.975006,2181.250000,777.600006,...,656.000000,280.569992,132.339996,1519.525024,3645.349976,180.154999,1567.600037,678.674988,714.699982,467.025009

In [11]:
data.loc['2015-03-30','^NSEI']

8436.52490234375

In [20]:
24%2.5

1.5